---
# - name: Disable SSH password auth
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     regexp: "^#PasswordAuthentication yes"
#     line: "PasswordAuthentication no"

# - name: Restart SSH deamon
#   service:
#     name: sshd
#     state: restarted
