# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-06T10:47:54Z"
  labels:
    app: transferpod
  name: transferpod
spec:
  containers:
  - args:
    - --provider
    - local
    - --basedir
    - /tmp
    env:
    - name: FORCE_HTTPS
      value: "false"
    - name: MAX_UPLOAD_SIZE
      value: "104857600"
    - name: PURGE_INTERVAL
      value: "2"
    - name: PUID
      value: "5000"
    - name: PGID
      value: "5000"
    image: localhost/transfer.sh-noroot:latest
    name: transfer.sh
    ports:
    - containerPort: 8080
      hostPort: 2323
    securityContext: {}
    volumeMounts:
    - mountPath: /tmp
      name: tmp-host-0
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: tmp-host-0
