# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /tmp:Z
  creationTimestamp: "2024-03-05T23:10:18Z"
  labels:
    app: wg-easy_pod
  name: wg-easy_pod
spec:
  containers:
  - args:
    - /usr/bin/dumb-init
    - node
    - server.js
    env:
    - name: PASSWORD
      value: password
    - name: WG_PORT
      value: "51820"
    - name: WG_HOST
      value: 192.168.1.42
    image: ghcr.io/wg-easy/wg-easy:latest
    name: wg-easy
    ports:
    - containerPort: 51821
      hostPort: 51821
    - containerPort: 51820
      hostPort: 51820
      protocol: UDP
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
        - CAP_NET_RAW
        - CAP_SYS_MODULE
    volumeMounts:
    - mountPath: /etc/wireguard
      name: root-host-0
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: root-host-0
